//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Illallangi Enterprises IllDea Git Library")]
[assembly: System.Reflection.AssemblyCompany("Illallangi Enterprises")]
[assembly: System.Reflection.AssemblyProduct("Illallangi Enterprises IllDea")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Illallangi Enterprises 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("Debug Build")]
[assembly: System.Runtime.InteropServices.Guid("d17e4cd1-5ed3-4712-8d58-8e15745e915a")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1")]


