//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("Illallangi Enterprises IllDea PowerShell Module")]
[assembly: System.Reflection.AssemblyCompany("Illallangi Enterprises")]
[assembly: System.Reflection.AssemblyProduct("Illallangi Enterprises IllDea")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Illallangi Enterprises 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("Debug Build")]
[assembly: System.Runtime.InteropServices.Guid("a4840885-5d36-42aa-8189-e7afded2c97e")]
[assembly: System.Reflection.AssemblyVersion("0.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.1")]


